image: docker:20.10.7

variables:
  # When using dind service, you must instruct Docker to talk with
  # the daemon started inside of the service. The daemon is available
  # with a network connection instead of the default
  # /var/run/docker.sock socket.
#  DOCKER_HOST: tcp://docker:2376
  DOCKER_HOST: tcp://localhost:2376
  #
  # The 'docker' hostname is the alias of the service container as described at
  # https://docs.gitlab.com/ee/ci/docker/using_docker_images.html#accessing-the-services.
  # If you're using GitLab Runner 12.7 or earlier with the Kubernetes executor and Kubernetes 1.6 or earlier,
  # the variable must be set to tcp://localhost:2376 because of how the
  # Kubernetes executor connects services to the job container
  # DOCKER_HOST: tcp://localhost:2376
  #
  # Specify to Docker where to create the certificates. Docker
  # creates them automatically on boot, and creates
  # `/certs/client` to share between the service and job
  # container, thanks to volume mount from config.toml
  DOCKER_TLS_CERTDIR: "/certs"
  # These are usually specified by the entrypoint, however the
  # Kubernetes executor doesn't run entrypoints
  # https://gitlab.com/gitlab-org/gitlab-runner/-/issues/4125
  DOCKER_TLS_VERIFY: 1
  DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"

services:
  - docker:20.10.7-dind
before_script:
  # https://gitlab.com/gitlab-org/gitlab-runner/-/issues/27384#note_497228752
  - |
    for i in $(seq 1 30)
    do
        docker info && break
        echo "Waiting for docker to start"
        sleep 1s
    done

  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build_zulu-alpine-clp:
  variables:
    CONTAINER_TAG: 13.0.7-3.13-Cbc2.10
    CONTAINER_NAME: zulu-alpine-clp
    CONTAINER_IMAGE: $CI_REGISTRY_IMAGE/$CONTAINER_NAME
  script:
    - docker build -t $CONTAINER_IMAGE:$CONTAINER_TAG -t $CONTAINER_IMAGE:latest .
    - docker push -a $CONTAINER_IMAGE
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
  tags:
    - kubernetes
  only:
    refs:
      - docker
    # only execute if dockerfile has changed
    changes:
      - "Dockerfile"
