name: build_CLP_osx


on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-10.15
    steps:
      - name: get new bash version
        run: brew install bash

      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache coin-or dependencies
        id: cache-coinor
        uses: actions/cache@v2
        with:
          path:  api/extern/coinor/osx/dist
          key: ${{ runner.os }}-coinor-cbc2.10.8

      - name: build coinor
        working-directory: api/extern/coinor
        shell: bash
        if: steps.cache-coinor.outputs.cache-hit != 'true'
        run: |
          export ADD_FFLAGS=-fallow-argument-mismatch
          export ADD_CXXFLAGS=-lrt # only use if getting the error: "undefined reference to `clock_gettime'"
          ./coinbrew build install Cbc@releases/2.10.8 --parallel-jobs 4 --verbosity 3 --tests none --prefix osx/dist

      - name: build CLPWrapper
        working-directory: api
        shell: bash
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build . --target install

      - name: CLPTest
        working-directory: api/build/test
        run: ./CLPTest

      - name: adapt runpaths
        working-directory: api/build/native/osx
        shell: bash
        run: ../../../../mac_utils/make_rpaths

      - name: upload
        working-directory: api/build/native/osx
        shell: bash
        run: |
          zip clp_osx.zip *
          curl --user '${{ secrets.CLOUD_USER }}:${{ secrets.CLOUD_PW }}' -T clp_osx.zip ${{ secrets.CLOUD_ADDRESS }}/clp_osx.zip
